sudo: required
language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "he305"
    token:
      secure: $SONAR_TOKEN

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - sonar-scanner
