version: '3'
services:
  db_twitch:
    image: postgres
    container_name: db_twitch
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: twitch_db
  app:
    image: 'twitch-producer:latest'
    restart: always
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db_twitch
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_twitch:5432/twitch_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin