spring:
  config:
    import: optional:file:.env[.properties]

jpa:
  properties:
      jdbc:
        lob:
          non_contextual_creation: true

twitch-client-id: ${twitch-client-id}
twitch-client-secret: ${twitch-client-secret}