spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://127.0.0.1:5444/twitch_db
    username: admin
    password: admin

jpa:
  properties:
    jdbc:
      lob:
        non_contextual_creation: true