spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://127.0.0.1:5444/twitch_db
    username: admin
    password: admin

jpa:
  properties:
    jdbc:
      lob:
        non_contextual_creation: true

twitch-producer.scheduler.delay: 5000000